// New IA. Hand-maintained for ordering and labels; tier flags propagate from frontmatter.
// Keep aligned with SECTIONS in ./types.ts and the directory structure under
// content/docs/. When you add a page, register it here in the right place.

export interface SidebarDoc {
  slug: string;
  title: string;
  tier?: 'community' | 'pro' | 'enterprise';
  status?: 'shipped' | 'planned';
}

export interface SidebarSection {
  slug: string;
  label: string;
  docs: SidebarDoc[];
}

export const sidebarData: SidebarSection[] = [
  {
    slug: 'start',
    label: 'Start here',
    docs: [
      { slug: 'start/what-is-grith', title: 'What is grith' },
      { slug: 'start/installation', title: 'Installation' },
      { slug: 'start/quickstart', title: 'Quickstart' },
      { slug: 'start/choose-your-agent', title: 'Choose your agent' },
      { slug: 'start/connect-a-model', title: 'Connect a model' },
      { slug: 'start/first-supervised-session', title: 'Your first supervised session' },
      { slug: 'start/reviewing-the-digest', title: 'Reviewing the digest' },
    ],
  },
  {
    slug: 'concepts',
    label: 'Concepts',
    docs: [
      { slug: 'concepts/threat-model', title: 'The threat model' },
      { slug: 'concepts/zero-trust', title: 'Zero-trust for agents' },
      { slug: 'concepts/three-phase-pipeline', title: 'Three-phase pipeline' },
      { slug: 'concepts/composite-scoring', title: 'Composite scoring' },
      { slug: 'concepts/quarantine-digest', title: 'The quarantine digest' },
      { slug: 'concepts/syscall-interception', title: 'Syscall interception' },
      { slug: 'concepts/supervisor-profiles', title: 'Supervisor profiles' },
      { slug: 'concepts/adaptive-reputation', title: 'Adaptive reputation' },
      { slug: 'concepts/taint-tracking', title: 'Taint tracking' },
      { slug: 'concepts/session-containment', title: 'Session containment' },
      { slug: 'concepts/canary-tokens', title: 'Canary tokens' },
      { slug: 'concepts/daemon-and-sessions', title: 'Daemon and thin-client sessions' },
    ],
  },
  {
    slug: 'cli',
    label: 'CLI reference',
    docs: [
      { slug: 'cli/overview', title: 'Overview' },
      { slug: 'cli/run', title: 'grith run' },
      { slug: 'cli/exec', title: 'grith exec' },
      { slug: 'cli/proxy-test', title: 'grith proxy test' },
      { slug: 'cli/digest', title: 'grith digest' },
      { slug: 'cli/audit', title: 'grith audit' },
      { slug: 'cli/log', title: 'grith log' },
      { slug: 'cli/canary', title: 'grith canary' },
      { slug: 'cli/supervisor', title: 'grith supervisor' },
      { slug: 'cli/daemon', title: 'grith daemon' },
      { slug: 'cli/profile-audit', title: 'grith profile audit' },
      { slug: 'cli/reputation', title: 'grith reputation' },
      { slug: 'cli/notifications', title: 'grith notifications' },
      { slug: 'cli/config', title: 'grith config' },
      { slug: 'cli/init', title: 'grith init' },
      { slug: 'cli/pro', title: 'grith pro', tier: 'pro' },
    ],
  },
  {
    slug: 'filters',
    label: 'Filter reference',
    docs: [
      { slug: 'filters/overview', title: 'Overview' },
      { slug: 'filters/phase-1-static', title: 'Phase 1 — static' },
      { slug: 'filters/phase-2-pattern', title: 'Phase 2 — pattern' },
      { slug: 'filters/phase-3-context', title: 'Phase 3 — context' },
      { slug: 'filters/01-operation-risk-scoring', title: '1. Operation risk scoring' },
      { slug: 'filters/02-static-path-matching', title: '2. Static path matching' },
      { slug: 'filters/03-sensitive-path-heuristic', title: '3. Sensitive path heuristic' },
      { slug: 'filters/04-allowlist-denylist', title: '4. Allowlist / denylist' },
      { slug: 'filters/05-argument-length-structure', title: '5. Argument length & structure' },
      { slug: 'filters/06-capability-enforcement', title: '6. Capability enforcement' },
      { slug: 'filters/07-secret-credential-scanning', title: '7. Secret / credential scanning' },
      { slug: 'filters/08-command-structure-analysis', title: '8. Command structure analysis' },
      { slug: 'filters/09-egress-policy', title: '9. Egress policy' },
      { slug: 'filters/10-dlp-gate', title: '10. DLP gate' },
      { slug: 'filters/11-canary-secret-detection', title: '11. Canary detection' },
      { slug: 'filters/12-destination-reputation', title: '12. Destination reputation' },
      { slug: 'filters/13-behavioural-anomaly', title: '13. Behavioural anomaly' },
      { slug: 'filters/14-taint-tracking', title: '14. Taint tracking' },
      { slug: 'filters/15-session-containment', title: '15. Session containment' },
      { slug: 'filters/16-rate-limiting', title: '16. Rate limiting' },
      { slug: 'filters/17-semantic-analysis', title: '17. Semantic analysis', status: 'planned' },
      { slug: 'filters/scoring-rules', title: 'Scoring rules' },
    ],
  },
  {
    slug: 'config',
    label: 'Configuration',
    docs: [
      { slug: 'config/overview', title: 'Overview & precedence' },
      { slug: 'config/general', title: '[general]' },
      { slug: 'config/proxy', title: '[proxy]' },
      { slug: 'config/reputation', title: '[reputation]' },
      { slug: 'config/digest', title: '[digest]' },
      { slug: 'config/llm', title: '[llm]' },
      { slug: 'config/supervisor', title: '[supervisor]' },
      { slug: 'config/server', title: '[server]' },
      { slug: 'config/filter-config-files', title: 'Filter config files' },
    ],
  },
  {
    slug: 'profiles',
    label: 'Supervisor profiles',
    docs: [
      { slug: 'profiles/how-profiles-work', title: 'How profiles work' },
      { slug: 'profiles/built-in-profiles', title: 'Built-in profiles' },
      { slug: 'profiles/claude-code', title: 'Claude Code' },
      { slug: 'profiles/codex', title: 'Codex' },
      { slug: 'profiles/aider', title: 'Aider' },
      { slug: 'profiles/goose', title: 'Goose' },
      { slug: 'profiles/copilot', title: 'GitHub Copilot' },
      { slug: 'profiles/cursor', title: 'Cursor' },
      { slug: 'profiles/cline', title: 'Cline' },
      { slug: 'profiles/openclaw', title: 'OpenClaw' },
      { slug: 'profiles/generic-cli', title: 'Generic CLI' },
      { slug: 'profiles/writing-a-custom-profile', title: 'Writing a custom profile' },
      { slug: 'profiles/profile-audit', title: 'Profile audit' },
      { slug: 'profiles/profile-drift', title: 'Profile drift', status: 'planned' },
    ],
  },
  {
    slug: 'api',
    label: 'API reference',
    docs: [
      { slug: 'api/overview', title: 'Overview' },
      { slug: 'api/health-and-tier', title: 'Health & tier' },
      { slug: 'api/audit', title: 'Audit' },
      { slug: 'api/digest', title: 'Digest' },
      { slug: 'api/proxy', title: 'Proxy' },
      { slug: 'api/supervisor', title: 'Supervisor sessions (IPC)' },
      { slug: 'api/canaries', title: 'Canaries' },
      { slug: 'api/notifications', title: 'Notifications' },
      { slug: 'api/analytics', title: 'Analytics', tier: 'pro' },
      { slug: 'api/sync-and-policies', title: 'Sync & policies', tier: 'pro' },
      { slug: 'api/reputation', title: 'Reputation (IPC)' },
      { slug: 'api/websocket', title: 'WebSocket /events' },
    ],
  },
  {
    slug: 'guides',
    label: 'Guides',
    docs: [
      { slug: 'guides/tuning-scoring-thresholds', title: 'Tuning scoring thresholds' },
      { slug: 'guides/writing-custom-filter-rules', title: 'Writing custom filter rules' },
      { slug: 'guides/setting-up-canary-tokens', title: 'Setting up canary tokens' },
      { slug: 'guides/notifications-slack', title: 'Notifications: Slack' },
      { slug: 'guides/notifications-discord', title: 'Notifications: Discord' },
      { slug: 'guides/notifications-telegram', title: 'Notifications: Telegram' },
      { slug: 'guides/notifications-teams', title: 'Notifications: Teams' },
      { slug: 'guides/notifications-email', title: 'Notifications: Email' },
      { slug: 'guides/notifications-webhook', title: 'Notifications: Webhook' },
      { slug: 'guides/notifications-pagerduty', title: 'Notifications: PagerDuty' },
      { slug: 'guides/notifications-opsgenie', title: 'Notifications: Opsgenie' },
      { slug: 'guides/notifications-whatsapp', title: 'Notifications: WhatsApp' },
      { slug: 'guides/notifications-desktop', title: 'Notifications: Desktop' },
      { slug: 'guides/notifications-websocket', title: 'Notifications: WebSocket' },
      { slug: 'guides/exfiltration-walkthrough', title: 'Exfiltration walkthrough' },
      { slug: 'guides/containment-walkthrough', title: 'Containment walkthrough' },
      { slug: 'guides/reverse-proxy-tls', title: 'Reverse proxy & TLS' },
      { slug: 'guides/team-setup', title: 'Team setup', tier: 'pro' },
      { slug: 'guides/encrypted-team-key-sync', title: 'Encrypted team key sync', tier: 'pro' },
      { slug: 'guides/air-gapped-deployment', title: 'Air-gapped deployment', tier: 'enterprise', status: 'planned' },
      { slug: 'guides/migrating-policy', title: 'Migrating policy' },
      { slug: 'guides/troubleshooting', title: 'Troubleshooting' },
    ],
  },
  {
    slug: 'security',
    label: 'Security',
    docs: [
      { slug: 'security/threat-model', title: 'Threat model' },
      { slug: 'security/trust-boundaries', title: 'Trust boundaries' },
      { slug: 'security/supervisor-only-assessment', title: 'Supervisor-only assessment' },
      { slug: 'security/notification-security', title: 'Notification security' },
      { slug: 'security/responsible-disclosure', title: 'Responsible disclosure' },
      { slug: 'security/advisories', title: 'Advisories' },
    ],
  },
  {
    slug: 'pro',
    label: 'Pro',
    docs: [
      { slug: 'pro/whats-in-pro', title: "What's in Pro", tier: 'pro' },
      { slug: 'pro/authentication', title: 'Authentication', tier: 'pro' },
      { slug: 'pro/license-lifecycle', title: 'License lifecycle', tier: 'pro' },
      { slug: 'pro/team-sync', title: 'Team sync', tier: 'pro' },
      { slug: 'pro/centralised-policies', title: 'Centralised policies', tier: 'pro' },
      { slug: 'pro/analytics-and-cost', title: 'Analytics & cost', tier: 'pro' },
      { slug: 'pro/encrypted-key-management', title: 'Encrypted key management', tier: 'pro' },
    ],
  },
  {
    slug: 'enterprise',
    label: 'Enterprise',
    docs: [
      { slug: 'enterprise/whats-in-enterprise', title: "What's in Enterprise", tier: 'enterprise' },
      { slug: 'enterprise/sso-saml', title: 'SSO & SAML', tier: 'enterprise', status: 'planned' },
      { slug: 'enterprise/rbac', title: 'RBAC', tier: 'enterprise', status: 'planned' },
      { slug: 'enterprise/compliance-reporting', title: 'Compliance reporting', tier: 'enterprise' },
      { slug: 'enterprise/siem-integration', title: 'SIEM integration', tier: 'enterprise' },
      { slug: 'enterprise/air-gapped-deployment', title: 'Air-gapped deployment', tier: 'enterprise', status: 'planned' },
    ],
  },
  {
    slug: 'ops',
    label: 'Operations',
    docs: [
      { slug: 'ops/running-as-a-daemon', title: 'Running as a daemon' },
      { slug: 'ops/performance-tuning', title: 'Performance & tuning' },
      { slug: 'ops/logging-and-audit-retention', title: 'Logging & audit retention' },
      { slug: 'ops/updates-and-profile-updates', title: 'Updates & profile updates' },
      { slug: 'ops/release-process', title: 'Release process' },
    ],
  },
  {
    slug: 'resources',
    label: 'Resources',
    docs: [
      { slug: 'resources/architecture-overview', title: 'Architecture overview' },
      { slug: 'resources/glossary', title: 'Glossary' },
      { slug: 'resources/faq', title: 'FAQ' },
      { slug: 'resources/changelog', title: 'Changelog' },
      { slug: 'resources/roadmap', title: 'Roadmap' },
    ],
  },
];
